name: Changelog

on: push

jobs:
  worker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: Generate Changelog
        run: git cliff --output CHANGELOG.md --config cliff.toml

      - name: Update Changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: Update Changelog.'